### ISSUE TITLE
kwinrc contains a key-only line that triggers an Exception

### ISSUE THREAD

**Issue by azmodude** [VorpalBlade/chezmoi_modify_manager#7]
Hi,

I am running Plasma 5.26.3 in a Wayland Session. Adding my `~/.config/kwinrc` via `chezmoi_ini_manager.py` works just fine, trying to later apply it again via `chezmoi` fails though:

```sh
azmo@hephaestus:~/.config> chezmoi apply ~/.config/kwinrc
Traceback (most recent call last):
File "/home/azmo/.local/share/chezmoi/.utils/chezmoi_modify_manager/bin/chezmoi_ini_manager.py", line 90, in load_ini
key, value = line.split("=", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/azmo/.local/share/chezmoi/.utils/chezmoi_modify_manager/bin/chezmoi_ini_manager.py", line 516, in <module>
main()
File "/home/azmo/.local/share/chezmoi/.utils/chezmoi_modify_manager/bin/chezmoi_ini_manager.py", line 506, in main
for line in process_target(
File "/home/azmo/.local/share/chezmoi/.utils/chezmoi_modify_manager/bin/chezmoi_ini_manager.py", line 202, in process_target
for data in load_ini(file):
File "/home/azmo/.local/share/chezmoi/.utils/chezmoi_modify_manager/bin/chezmoi_ini_manager.py", line 93, in load_ini
raise ParseException(f"Error while processing line {line}") from e
__main__.ParseException: Error while processing line AnimationSpeed[$d]

chezmoi: exit status 1
```

The corresponding line in my `kwinrc` looks like this:

```
[...]
[Compositing]
AnimationSpeed[$d]
[...]
```

There is just a key present, no value. I tried manually adding a value to the `AnimationSpeed` key (can't really find a `System Settings` option for it), but `kwin` changed it back to key-only after logging in again.

Thanks!

**Comment by VorpalBlade** [comment]
While I don't see this particular line on my system, I do have similar lines in `khotkeysrc`, a file I currently manage with plain chezmoi.

**Comment by VorpalBlade** [comment]
Thanks for the report. Issue should be fixed now. Please re-open should the issue persist.

**Comment by azmodude** [comment]
Thank you very much for the quick fix - can confirm everything is great again. :thumbsup:

Especially liking the `# KDE has some lines without values. This is terrible.` comment - couldn't agree more.
